apiVersion: batch/v1
kind: CronJob
metadata:
  name: onetimejob
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    metadata:
      name: onetimejob
    spec:
      template:
        spec:
          containers:
          - image: crackitty/onetimejob:1.0
            imagePullPolicy: IfNotPresent
            name: onetimejob
            resources: {}
          restartPolicy: OnFailure
